- name: Installing Nginx and Starting Service
  hosts: mongodb
  remote_user: root #this will provide ansible root access.
  
  tasks:
  - name: install Nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: starting Nginx
    ansible.builtin.service:
      name: nginx
      state: started