- name: printing 
  hosts: mongodb
  vars:
    NAME: Laksh
    PERSON: AYUSH
    SAY: good and you..?
  tasks:
  - name: print Hello
    ansible.builtin.debug:
      msg: "hello{{NAME}}, How are you. {{PERSON}} {{SAY}}?"