- name: Installing Shipping components
  hosts: localhost
  become: yes
  tasks:
    - name: Install maven
      ansible.builtin.yum:
        name: maven
        state: installed

    - name: checking
      ansible.builtin.command: id roboshop
      register: output1
      ignore_errors: true

    - name: print command out
      ansible.builtin.debug:
        msg: "output is: {{output1}}"

    - name: print exit status
      ansible.builtin.debug:
        msg: "{{output1.rc}}"

    - when: output1.rc != 0
      name: create user roboshop
      ansible.builtin.user:
        name: roboshop
        state: present
        
    - name: checking dir
      ansible.builtin.stat:
        path: /app
      register: dir_info
    
    - name: creating dir if not exist
      when: not dir_info.stat.exists
      ansible.builtin.file:
        path: /app
        state: directory
        mode: '0755'

    - name: Perform tasks when directory exists
      ansible.builtin.debug:
        msg: "Directory exists, proceed with tasks"
      when: dir_info.stat.exists
      
    - name: Downloading application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp/shipping.zip
    
    - name: unziping Shipping
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
    
    - name: installing dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app
    
    - name: Move file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: copying catalogue.service
      ansible.builtin.copy:
        src: shipping.service
        path: /etc/systemd/system/shipping.service

    - name: Reload systemd daemon and restart a service
      ansible.builtin.systemd:
        daemon_reload: yes
    
    - name: Install MySql
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: load mysql schema
      ansible.builtin.shell: mysql -h mysql.laksh.site -uroot -pRoboShop@1 < /app/schema/shipping.sql

    - name: restart shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: true